# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: amio/node-chrome

pipelines:
  branches:
    master:
    - step:
        name: Test
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run test
    - step:
        name: Build
        script:
          - npm run build
        artifacts: # defining the artifacts to be passed to each future step.
          - dist/**
    - step:
        name: Deploy to production
        deployment: test
        script:
          - pipe: atlassian/firebase-deploy:0.2.2
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $PROJECT_ID
