# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: amio/node-chrome

pipelines:
  default:
    - step:
        name: Build and Tets
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run test
          - npm run build
    - step:
        name: Deploy to test
        deployment: test
        script:
          - pipe: atlassian/firebase-deploy:0.2.2
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
