image: amio/node-chrome

pipelines:
  default: # For all branches other than master, run tests to determine successful build.
    - step:
        name: Test
        caches:
          - node
        script:
          - npm install
          - npm run test
  branches:
    master:
    - step:
        name: Test
        caches:
          - node
        script:
          - npm install
          - npm run test
    - step:
        name: Build
        caches:
          - node
        script:
          - npm run build
        artifacts: # defining the artifacts to be passed to future step.
          - dist/**
    - step:
        name: Deploy to production
        caches:
          - node
        deployment: test
        script:
          - pipe: atlassian/firebase-deploy:0.2.2
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $PROJECT_ID
